In [1]:
import pandas as pd
df = pd.read_csv("sample.csv", sep = ",")
df

,Accession,Title,Sample Type,Taxonomy,Channels,Platform,Series,Supplementary Types,Supplementary Links,SRA Accession,Contact,Release Date
0,GSM2171880,21yr_male_cell1,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2171...,SRX1787822,Martin Enge,"Sep 28, 2017"
1,GSM2171881,21yr_male_cell2,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2171...,SRX1787823,Martin Enge,"Sep 28, 2017"
2,GSM2171882,21yr_male_cell3,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2171...,SRX1787824,Martin Enge,"Sep 28, 2017"
3,GSM2171883,21yr_male_cell4,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2171...,SRX1787825,Martin Enge,"Sep 28, 2017"
4,GSM2171884,21yr_male_cell5,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2171...,SRX1787826,Martin Enge,"Sep 28, 2017"
...,...,...,...,...,...,...,...,...,...,...,...,...
2539,GSM2174421,22yr_male_cell2540,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2174...,SRX1790361,Martin Enge,"Sep 28, 2017"
2540,GSM2174422,22yr_male_cell2541,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2174...,SRX1790362,Martin Enge,"Sep 28, 2017"
2541,GSM2174423,22yr_male_cell2542,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2174...,SRX1790363,Martin Enge,"Sep 28, 2017"
2542,GSM2174424,22yr_male_cell2543,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2174...,SRX1790364,Martin Enge,"Sep 28, 2017"
2543,GSM2174425,22yr_male_cell2544,SRA,Homo sapiens,1,GPL18573,GSE81547,CSV;SRA Run Selector,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2174...,SRX1790365,Martin Enge,"Sep 28, 2017"

In [3]:
df["Age"] = df["Title"].apply(lambda x: x.split("yr")[0])
df["Age"] = df["Age"].astype(int)
df

count    2544.000000
mean       25.443789
std        17.092678
min         1.000000
25%         6.000000
50%        22.000000
75%        38.000000
max        54.000000
Name: Age, dtype: float64

In [32]:
import os
p = './GSE81547_data/'
cells = pd.DataFrame()

for filename in os.listdir(p):
    f = os.path.join(p,filename)
    if os.path.isfile(f):
        cellname = f.split("_")[1].split("/")[1]
        cell = pd.read_csv(f, sep = "\t", header = None)
        cell = cell.pivot_table(columns = 0, values = 1)
        cell.rename(index={1:cellname}, inplace=True)
        cells = pd.concat([cells,cell])
cells

,1/2-SBSRNA4,A1BG,A1BG-AS1,A1CF,A2LD1,A2M,A2ML1,A2MP1,A4GALT,A4GNT,...,ZYG11B,ZYX,ZZEF1,ZZZ3,alignment_not_unique,ambiguous,no_feature,not_aligned,tAKR,too_low_aQual
GSM2171880,0,0,0,0,0,0,0,0,0,0,...,0,0,0,651,85563,3754,407558,0,0,0
GSM2171881,0,0,0,0,0,0,0,0,0,0,...,320,2,0,152,70223,4592,359410,0,0,0
GSM2171882,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,39277,4473,172353,0,0,0
GSM2171883,0,0,0,2,0,0,0,0,0,0,...,0,3,66,14,86043,2618,596866,0,0,0
GSM2171884,0,0,0,0,0,0,0,0,0,0,...,578,0,0,0,45023,2342,275800,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM2174421,0,0,0,0,0,1253,0,0,0,0,...,0,0,0,0,77533,6142,186226,0,0,0
GSM2174422,0,0,0,0,0,0,0,0,0,0,...,73,0,0,0,84350,9231,388780,0,0,0
GSM2174423,0,0,0,0,0,2724,0,0,0,0,...,0,29,0,0,52278,3883,194324,0,0,0
GSM2174424,0,0,0,83,0,0,0,0,0,0,...,0,6,49,0,81459,3700,318373,0,0,0
GSM2174425,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,38748,1548,214199,0,0,0

In [33]:
cells.to_csv("GSE81547.csv", sep = ",", index = True)

In [36]:
#df.set_index("Accession", inplace = True)
df["Age"].to_csv("Ages.csv", sep = ",", index = True)